- hosts: all
  roles:
    - role: ansible-threatstack
      threatstack_deploy_key: "{{ threatstack_deploy_key }}"
      threatstack_ruleset: "{{ threatstack_ruleset}}"
      threatstack_pkg: "{{ threatstack_pkg }}"

